name: Configure Azure
description: Configure Azure credentials for Terraform

inputs:
  ARM_CLIENT_ID:
    description: ARM_CLIENT_ID
    required: true
  ARM_CLIENT_SECRET:
    description: ARM_CLIENT_SECRET
    required: true
  ARM_SUBSCRIPTION_ID:
    description: ARM_SUBSCRIPTION_ID
    required: true
  ARM_TENANT_ID:
    description: ARM_TENANT_ID
    required: true

runs:
  using: "composite"
  steps:
    - name: Export Azure credentials
      id: azure-credentials
      shell: bash
      run: |
        echo "{
          \"clientId\": \"$ARM_CLIENT_ID\",
          \"clientSecret\": \"$ARM_CLIENT_SECRET\",
          \"subscriptionId\": \"$ARM_SUBSCRIPTION_ID\",
          \"tenantId\": \"$ARM_TENANT_ID\"
        }" >> "$GITHUB_OUTPUT"
      env:
        ARM_CLIENT_ID: ${{ inputs.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ inputs.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ inputs.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ inputs.ARM_TENANT_ID }}

    - name: Azure login
      uses: azure/login@v2
      with:
        creds: ${{ steps.azure-credentials.outputs.stdout }}
