name: Provision Environment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  plan-and-apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.1

      - name: Terraform Init
        run: terraform init
        working-directory: infra
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

      - name: Terraform Plan
        run: terraform plan -out=tf.plan -input=false && terraform show -no-color tf.plan > tf.plan.txt
        working-directory: infra

      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: tf-plan
          path: infra/tf.plan.txt

      - name: Terraform Apply
        run: terraform apply -input=false tf.plan
        working-directory: infra